[[smesh]]
arch = "aarch64"
git-tree-sha1 = "e0c7979a5b6c1db10c9da16ce97e74e749c1092c"
libgfortran_version = "5.0.0"
os = "macos"

    [[smesh.download]]
    sha256 = "611686dba3cfaadda943d297175c1ee6d013fa10ead516968ba68e13ca75bbb5"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.aarch64-apple-darwin-libgfortran5.tar.gz"
[[smesh]]
arch = "aarch64"
git-tree-sha1 = "7c677ddf2ba243a4d87b73e1ba639c13eea2278a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "1ccb157f550f38ba01ec07b98cf56b1857c461edf4d538da19538f287ba4953a"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.aarch64-linux-gnu-libgfortran5.tar.gz"
[[smesh]]
arch = "aarch64"
git-tree-sha1 = "00a43e30ae0f47788d2e840e21bc3b9cfd0b2f4e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "3d21a4bc14b2568bf5d99a566edc75070a7a327d443d962938891ca844f95ed0"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.aarch64-linux-musl-libgfortran5.tar.gz"
[[smesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fbd1458e9676537a9ab711b1190a686dbdb1f17d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "9577c53d05b3f0773e0f0fd62ec2eb9ba911234462d8220130b49d3f4784de12"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[smesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "86836e6ea62171db9680d41040ac60a7a0943663"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "877c7625242831bbfe84b678fae71e8a0513bc3ea12e2db67a994b7056cc3ef0"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[smesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f35ef3da74786b545269f12d85f116008878216e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "bef3352b890ec1a6fcd9679cd1c1bff09fc3ff64537407bddb8f8de6ea346bc6"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[smesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6a21ef7b2b4871ef3a3ce3f88350f44aa09ca312"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "90e29f0bff033df5629e6d74ef9354015450702c2b5efc0c0eb74a305b28a1bb"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[smesh]]
arch = "i686"
git-tree-sha1 = "f532a77eb4c3d622fb4886b4cdc2a6e6efa54394"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "e9df7b90b20dad1c5d554cc933b8bebe7a432d873dce78469d02a0beaa374fd4"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.i686-linux-gnu-libgfortran5.tar.gz"
[[smesh]]
arch = "i686"
git-tree-sha1 = "163839eb89ecdec4d958cf924e0669e49857893a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "18aba963b7fb981a048ebaaa72610f3a42d7fee5a4c5d0b57c7e08f4e110d97b"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.i686-linux-musl-libgfortran5.tar.gz"
[[smesh]]
arch = "i686"
git-tree-sha1 = "b91c802f772976ee24fc90c5fdbbb5c0cf1f8534"
libgfortran_version = "5.0.0"
os = "windows"

    [[smesh.download]]
    sha256 = "843782ace2de8a80331846256b9e01d5ef9924fdbc5fda894a655d85b772c643"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.i686-w64-mingw32-libgfortran5.tar.gz"
[[smesh]]
arch = "powerpc64le"
git-tree-sha1 = "83be9f08b9dd14f933806f5a4e82097c9353eb66"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "742bd6b488d9658953d22a3710f84c34eb92c93d4ed5a5a2875d816878bd0a7a"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[smesh]]
arch = "x86_64"
git-tree-sha1 = "b696ffe0ea011e3175bb79bf1d1d602beed24e93"
libgfortran_version = "5.0.0"
os = "macos"

    [[smesh.download]]
    sha256 = "3cde6b2d772e8189bac96fc91dc9eae3390c4b41f498929dfa29da8229da7f98"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.x86_64-apple-darwin-libgfortran5.tar.gz"
[[smesh]]
arch = "x86_64"
git-tree-sha1 = "b2148a92c0984975d31a3cbfacb61e4f446a3c45"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "342877b5c9926ec3e78c0520236e4efdf718c3d464901613ec19c80043fe8fdf"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.x86_64-linux-gnu-libgfortran5.tar.gz"
[[smesh]]
arch = "x86_64"
git-tree-sha1 = "bf58a61a5de4a6bdb2596d7c03e8237015c99ace"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "ba9a3af72255d20787b7dff929e285d28b3d56b094044c54aeba982d735d4da9"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.x86_64-linux-musl-libgfortran5.tar.gz"
[[smesh]]
arch = "x86_64"
git-tree-sha1 = "035fc5a9dae720af30d2a27d4bd6b05154636507"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[smesh.download]]
    sha256 = "781316fe29ef597f55894000cf6bb9ed4718401a8aaa0ec894161f4985d84206"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[smesh]]
arch = "x86_64"
git-tree-sha1 = "f96283694178343cec369923d92aabe5515db3ff"
libgfortran_version = "5.0.0"
os = "windows"

    [[smesh.download]]
    sha256 = "b39108d94e3c2bdf4afe12900ce6d0727669cc80aec7cfbee4ffb1c5402e0a92"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.3+0/smesh.v0.1.3.x86_64-w64-mingw32-libgfortran5.tar.gz"
