[[smesh]]
arch = "aarch64"
git-tree-sha1 = "04737178314717cc2ceccde8b2b2a111e528641b"
libgfortran_version = "5.0.0"
os = "macos"

    [[smesh.download]]
    sha256 = "76216282a0e51690d2460920b1327d67e093ea6f4712bf3d7b41827528f061bb"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[smesh]]
arch = "aarch64"
git-tree-sha1 = "13fae570f67cde869f9d368d52916599d4230bb7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "df23eb6e504779d6cd3cdf0baf295484e6821b06a479bd5a5e489dbdde4b7eb2"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[smesh]]
arch = "aarch64"
git-tree-sha1 = "620f5ded282d78a653a4d303eb6bf82b46187e8e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "b1b8efb3498424b3b6fff78d219ac00dc0e7e6101f7fdd5f7845ad0bf6ae5ffb"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[smesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3ba7d418ebdc133f42485269adca9d1380eba866"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "19bf99af8a19e6e97870c8c2d3a0aeb8f7c445ddada20f8c1106b888cdf6c3a5"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[smesh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bd3282b4813fe4eac07ddb449cef536b8c8374ba"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "2de72b31d84654fc51328d3871706b362f49a605cc99578311755fd2b0b23dd5"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[smesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b0b0930a8b44b6b482eb333c52c0b0d1e60a0bde"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "70411a6cab743415d72aeb9bde57b8ac88969aeac45e05f4a2045cc8d891a7d1"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[smesh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31f598750fdd776c054b6147bf88027f0a47c2d5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "347dfab24b89cbd4918d60d24bc58f812427fa2abd05bdfc46bd9d15c311e78a"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[smesh]]
arch = "i686"
git-tree-sha1 = "ca81ddbf58b4f21494e3e2f1a257cdf4a15efaa3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "e7e54ee2c111af3f209ec89a72457ccc1218929feaabfe95d34463d4843d09e1"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.i686-linux-gnu-libgfortran5.tar.gz"
[[smesh]]
arch = "i686"
git-tree-sha1 = "a3e4025c62320b2e0e51b358e33dcb955da5fd05"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "0c90efda7d3587951d6b5cdfd4426190d5c534a4a123d22205bbce499d3388be"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.i686-linux-musl-libgfortran5.tar.gz"
[[smesh]]
arch = "i686"
git-tree-sha1 = "60ae4cf334ddac8c6972036782035f7917e693e5"
libgfortran_version = "5.0.0"
os = "windows"

    [[smesh.download]]
    sha256 = "caeb52a749b37224d9428321e1e3b6b9fbffa52fe6a52fe8f8661ecbb73b0e9e"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[smesh]]
arch = "powerpc64le"
git-tree-sha1 = "9e00178d89170de44a631fbf551600f86dbb633f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "fe2fa85ebed68900b4d5e5e2ff419537d6a1d2af554769d6e27e75727a2a9581"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[smesh]]
arch = "x86_64"
git-tree-sha1 = "7c57a13e6443d7cef99e12361db591f43ac5036b"
libgfortran_version = "5.0.0"
os = "macos"

    [[smesh.download]]
    sha256 = "37ba5d6226beabe61ad3e0946381178872cfba595f2dfd250d2baab828b6c442"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[smesh]]
arch = "x86_64"
git-tree-sha1 = "eade31e207b41543932b1dd6a0363a01770b863d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "84cfcb670c7f43a80f9ed2cb85160de0f66e3b2fb2dec3a3dd0a138b25e9c32f"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[smesh]]
arch = "x86_64"
git-tree-sha1 = "e2c366f2352b9b233ac6b0f9352abf3bc62afb47"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[smesh.download]]
    sha256 = "e098fed0b575c19087d398b6ce6003f8ec076d584985c258190bcc9b1c8a23ed"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[smesh]]
arch = "x86_64"
git-tree-sha1 = "3da02e073494150ee023cf5be4e3cc8498fa5b5d"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[smesh.download]]
    sha256 = "b535a35907a1c37417d2a119a3d771b0c18e478e9b8fd865b4982c5a777a0114"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[smesh]]
arch = "x86_64"
git-tree-sha1 = "da03f14c5768fa73e43b4a00e6df1b60b743221a"
libgfortran_version = "5.0.0"
os = "windows"

    [[smesh.download]]
    sha256 = "7592ce3685e95802e3ac55b55c325a195e7e15dac6bb363fc117da75dcff0251"
    url = "https://github.com/JuliaBinaryWrappers/smesh_jll.jl/releases/download/smesh-v0.1.2+0/smesh.v0.1.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
