# Autogenerated wrapper script for smesh_jll for x86_64-w64-mingw32-libgfortran5
export libsmesh, libsmesh_io, mesh_run

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("smesh")
JLLWrappers.@declare_library_product(libsmesh, "libsmesh.dll")
JLLWrappers.@declare_library_product(libsmesh_io, "libsmesh_io.dll")
JLLWrappers.@declare_executable_product(mesh_run)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libsmesh,
        "bin\\libsmesh.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsmesh_io,
        "bin\\libsmesh_io.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        mesh_run,
        "bin\\smesh_run.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
